temp-meters-topic: temp_records_topic
press-meters-topic: press_records_topic
sink-topic: sink_topic
kafka-bootstrap-servers: kafka:9092
enrichment-endpoint: http://127.0.0.1:80/enrichment
disable-operators-chain: false
kafka-params:
  group.id: main-consumer
  transaction.timeout.ms: 900000